### ISSUE TITLE
USER STORY: Add poll for choosing next running location

### ISSUE THREAD

**Issue by niekados** [niekados/My-First-Agile-Project#7]
As an **administrator** I can **create a poll listing the next run locations** so that **we can organise a run in the best location for the majority of participants**

## Acceptance Criteria:

- Additional option to original polls.
- Have three options.
- Use radio buttons.

## Tasks:

- [ ] Add a separate section for voting next run to the poll.
- [ ] Add 3 entry fields for custom locations.
- [ ] Add radio buttons for entry fields to HTML.
