### ISSUE TITLE
USER STORY: Manage Poll

### ISSUE THREAD

**Issue by niekados** [niekados/My-First-Agile-Project#8]
As an **administrator** I can **manage the poll** so that **I can customize the poll**

## Acceptance Criteria:

- Add a question to the poll.
- Add response options to the poll.
- Submit the poll.

## Tasks

- [ ] An HTML form section to add a poll question.
- [ ] An HTML radio buttons for the options for answers.
- [ ] Add submit button.
