### ISSUE TITLE
USER STORY: Retrieve poll statistics/results

### ISSUE THREAD

**Issue by niekados** [niekados/My-First-Agile-Project#9]
As an **administrator** I can **retrieve poll results** so that **I can plan for the upcoming runs**

## Acceptance Criteria:

- Menu button to review poll results.
- List all polls by date.
- Display poll responses in percentages. 

## Tasks

- [ ] Create a button for retrieving poll results.
- [ ] Create a new page for listing all poll results.
- [ ] Create a results page.
- [ ] Setup Python to store and calculate poll data.
